# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  start-app-run-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install
      run: npm install
    - name: start-test-app
      run: npm start &
      env:
        CI: true
    - name: Install dependencies
      run: npm install
    - name: Install playwright
      run: npx playwright install
    - name: Wait for the server to be ready
      run: |
          echo "Waiting for the server to be ready..."
          npx wait-on http://localhost:3000
    - name: Run playwright tests
      run: npx playwright test tests

  deploy:
    runs-on: ubuntu-latest
    needs: start-app-run-tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
          wait-for-success: true